import React from "react";
import Router from "next/router";
import DashboardLayout from '../../components/layouts/dashboard';
import AuthService from "../../src/services/AuthService";
import { connect } from 'react-redux';
import actions from '../../redux/actions/auth';
import {handleResponseErrorForComponent} from "../../src/utils/errorsHandler";
import { Card, Form, FormGroup, Label, Input, FormText } from 'reactstrap';
import api from '../../src/api';

class BotsPage extends React.Component {
    static async getInitialProps(context) {
        AuthService.initialShouldAuthorized(context);
    }

    constructor(props) {
        super(props);
        this.state = {
            loading: false,
            form: {
                label: '',
                token: '',
            },
            fails: {},
        };
    }

    handleSubmit(e) {
        e.preventDefault();
        if (this.state.loading) {
            return;
        }
        const self = this;
        self.setState({loading: true, fails: {}});
        api.bots.create(this.state.form)
            .then(response => {
                self.setState({loading: false});
                Router.push('/bots');
            })
            .catch(
            (err) => {
                self.setState({loading: false});
                handleResponseErrorForComponent(err, self);
            }
        );
    }

    handleChange = ({ target }) => {
        let fails = Object.assign({}, this.state.fails);
        delete fails[target.name];
        this.setState({ form: {...this.state.form, [target.name]: target.value}, fails });
    };

    render() {
        return <DashboardLayout title="Bot creation">
            <div className="d-flex flex-row align-items-center mb-3">
                <h5 className="mb-0 mr-3">Bot creation</h5>
            </div>
            <Card body>
                <Form onSubmit={this.handleSubmit.bind(this)}>
                    <FormGroup className={this.state.fails.hasOwnProperty('label') ? 'form-error' : ''}>
                        <Label>Label</Label>
                        <Input
                            name="label"
                            type="text"
                            placeholder="Enter a label"
                            className={this.state.fails.hasOwnProperty('label') ? 'is-invalid' : ''}
                            value={this.state.form.label}
                            onChange={this.handleChange}
                            disabled={this.state.loading}
                            required
                            autoFocus />
                        <div className="invalid-feedback">
                            {this.state.fails.label}
                        </div>
                        <FormText className="text-muted">
                            Label for identify a bot
                        </FormText>
                    </FormGroup>

                    <FormGroup>
                        <Label>Token</Label>
                        <Input
                            name="token"
                            type="text"
                            placeholder="Enter a token"
                            value={this.state.form.token}
                            className={this.state.fails.hasOwnProperty('token') ? 'is-invalid' : ''}
                            onChange={this.handleChange}
                            disabled={this.state.loading}
                            required />
                        <div className="invalid-feedback">
                            {this.state.fails.token}
                        </div>
                        <FormText className="text-muted">
                            A token that was generated by telegram
                        </FormText>
                    </FormGroup>
                    <button className="btn btn-success" type="submit">Add</button>
                </Form>
            </Card>
        </DashboardLayout>
    }
}

export default connect(
    state => state,
    actions
)(BotsPage);
